---
- name: start an instance and Add EBS
  ec2_instance:
    name: "master-testing"
    region: us-east-2
    vpc_subnet_id: subnet-067e20746d2eb0255
    image_id: ami-077e31c4939f6a2f3
    instance_type: m5.2xlarge
    key_name: "omkarmangalekar"
    volumes:
      - device_name: /dev/xvda
        ebs:
          volume_size: 80
          delete_on_termination: true
    wait: yes
    tags:
      Owner: Omkar
      Environment: Testing 
